### ISSUE TITLE
Unable to highlighting opening tag?

### ISSUE THREAD

**Issue by CodingNinjaOctocat** [tomasr/viasfora#198] opened 2017-04-28 16:12 UTC
For the XML/XAML, the closing tag can be highlighting, but the opening tag can't be highlighting!?
it is a bug?

**Comment by tomasr** [comment] 2017-04-28 16:15
It's not a bug. The feature specifically is highlighting the closing tag in a different color than the opening tag (it's a feature in Vim colorschemes I love, as it makes XML files much easier to read).

If you want to color the opening tag in a different color, just change the default XML Element color in Visual Studio.

Or if you want to keep the default behavior in Visual Studio, just disable the feature in Viasfora by setting Tools -> Options -> Viasfora -> XML Editor -> Higlight XML Closing Tags to False.

**Comment by CodingNinjaOctocat** [comment] 2017-04-28 16:27
Thank you for your reply. 
I just found out that my vs is dark theme, the default opening tag is white (really ugly, a bunch of white), and then VSF will be closing tag rendered into orange, it seems somewhat weird.

**Comment by tomasr** [comment] 2017-04-28 16:29
The default dark theme in VS uses blue for the opening tags, so the two colors work well together. The default light/blue themes use red, so again, it matches OK.

That said, you can change both colors to match whatever your preference is.

**Comment by CodingNinjaOctocat** [comment] 2017-04-28 16:33
The default dark theme in my VS2017 uses white for the opening tags! It seems I want to change the color manually😅
Thanks again!

**Closed** 2017-04-28 16:35 UTC
Labels: invalid
