### ISSUE TITLE
Use italics on Flow Control Keywords option does not work in VS2019 RC3

### ISSUE THREAD

**Issue by mzhukovs** [tomasr/viasfora#270] opened 2019-03-25 06:24 UTC
When switching this option to True in the settings:
![image](https://user-images.githubusercontent.com/13161978/54899056-879ca200-4f09-11e9-8a2a-86b62e7e5e94.png)

It has no impact on the flow control keywords (i.e. they remain non-italicized), perhaps because it is still pointing to the old, regular "Keyword" keywords instead of the new "Keyword - Control" keywords?

**Comment by tomasr** [comment] 2019-03-25 11:53
Duplicate of issue #268

**Closed by tomasr** 2019-03-25 11:53 UTC
Labels: duplicate

**Comment by TymurGubayev** [comment] 2024-05-16 17:42
@tomasr 
sry to revive this, but Flow Control Keywords highlighting doesn't work for me for some reason (VS 2022 17.9.7, but it didn't for quite some time now). Is there some obscure setting somewhere, or how could I debug this issue? Other features do work just fine.
