### ISSUE TITLE
An Error Happened

### ISSUE THREAD

**Issue by MarkSky** [tomasr/viasfora#217] opened 2017-08-23 02:40 UTC
Visual Studio Version: 15.3.2
Viasfora Version: 3.6.147

When I edit the .vue file,  there is an error happened.
And Visual Studio write a log:

```
<entry>
    <record>2022</record>
    <time>2017/08/23 02:30:37.432</time>
    <type>Error</type>
    <source>Viasfora</source>
    <description>GetCurFile. Exception: System.InvalidOperationException: GetCurFile returned 0x80004001</description>
  </entry>
  <entry>
    <record>2023</record>
    <time>2017/08/23 02:30:37.434</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.InvalidOperationException: GetCurFile returned 0x80004001&#x000D;&#x000A;   &#x65BC; Winterdom.Viasfora.TextEditor.CheckError(Int32 hr, String operation)&#x000D;&#x000A;   &#x65BC; Winterdom.Viasfora.TextEditor.GetFileName(ITextBuffer buffer)&#x000D;&#x000A;   &#x65BC; Winterdom.Viasfora.Outlining.UserOutliningManager.LoadRegions(ITextBuffer buffer)&#x000D;&#x000A;   &#x65BC; Winterdom.Viasfora.Outlining.UserOutliningManager.&lt;&gt;c__DisplayClass1_0.&lt;Get&gt;b__0()&#x000D;&#x000A;   &#x65BC; Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)&#x000D;&#x000A;   &#x65BC; Winterdom.Viasfora.Outlining.UserOutliningManager.Get(ITextBuffer buffer)&#x000D;&#x000A;   &#x65BC; Winterdom.Viasfora.Outlining.UserOutliningTaggerProvider.CreateTagger[T](ITextBuffer buffer)&#x000D;&#x000A;   &#x65BC; Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)&#x000D;&#x000A;--- &#x5148;&#x524D;&#x64F2;&#x56DE;&#x4F8B;&#x5916;&#x72C0;&#x6CC1;&#x4E4B;&#x4F4D;&#x7F6E;&#x4E2D;&#x7684;&#x5806;&#x758A;&#x8FFD;&#x8E64;&#x7D50;&#x5C3E; ---&#x000D;&#x000A;   &#x65BC; Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
```

**Comment by tomasr** [comment] 2017-08-23 02:41
Duplicate of #216.

**Closed by tomasr** 2017-08-23 02:41 UTC
Labels: duplicate
