### ISSUE TITLE
Exception in VS2017 15.6

### ISSUE THREAD

**Issue by fdncred** [tomasr/viasfora#232] opened 2018-03-08 13:10 UTC
I've begun seeing an exception happening frequently since I updated Visual Studio to 15.6.  This is what is in my Activity.log.
```
System.NullReferenceException: Object reference not set to an instance of an  object. at  Winterdom.Viasfora.Util.ToolTipWindow.TipTextViewModel.GetNearestPointInVisualSnapshot(SnapshotPoint  editBufferPoint, ITextSnapshot targetVisualSnapshot, PointTrackingMode  trackingMode) at
Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.OnClassificationChanged(Object  sender, ClassificationChangedEventArgs e) at  
Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierAggregator.OnBatchedTagsChanged(Object  sender, BatchedTagsChangedEventArgs e) at  
Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object  sender, EventHandler`1 eventHandlers, TArgs args)
```
Any tips on how to avoid it?
My version of Viasfora is 3.8.157.

Thanks,
Darren

**Comment by tomasr** [comment] 2018-03-08 13:20
Duplicate of #231, will handle there

**Closed by tomasr** 2018-03-08 13:20 UTC
Labels: duplicate
